AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "root"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action: "cloudformation:CreateStack"
              Resource: "*"
            - Effect: Allow
              Action: "ec2:CreateVpc"
              Resource: "*"
            - Effect: Allow
              Action: "ec2:CreateSubnet"
              Resource: "*"
            - Effect: Allow
              Action: "ec2:CreateNatGateway"
              Resource: "*"
            - Effect: Allow
              Action: "ec2:CreateRoute"
              Resource: "*"
            - Effect: Allow
              Action: "ec2:CreateRouteTable"
              Resource: "*"
            - Effect: Allow
              Action: "ec2:CreateInternetGateway"
              Resource: "*"
            - Effect: Allow
              Action: "ec2:CreateNetworkAcl"
              Resource: "*"
            - Effect: Allow
              Action: "ec2:CreateNetworkAclEntry"
              Resource: "*"
            - Effect: Allow
              Action: "ec2:CreateSecurityGroup"
              Resource: "*"
      RoleName: CloudFormationRole
